### PR TITLE
Use inherits module instead of util to reduce browserified size

### PR DESCRIPTION
**Pull request by bendrucker**
When bundled with browserify, this cuts the size from 3.44kb to 618b

### CODE REVIEW

**Comment by mdlavin** [comment]
I like this change, but it looks like more changes are needed in the tests.  If you can fix up the test, I'm happy to merge it.

**Comment by bendrucker** [comment]
Whoops, forgot to change the module ID there. Passing!

**Comment by mdlavin** [comment]
Looks great.  Thanks for the improvement.  I'll push a new NPM version quickly

**Comment by bendrucker** [comment]
Awesome, thank you!

**Pull request merged**
